repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-merge-conflict
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: check-case-conflict
  - repo: local
    hooks:
      - id: run-format
        name: Run formatters
        entry: make format
        language: system
        pass_filenames: false
        always_run: true

      - id: run-lint
        name: Run linters
        entry: make lint
        language: system
        pass_filenames: false
        always_run: true

      - id: run-test
        name: Run tests
        entry: make test
        language: system
        pass_filenames: false
        always_run: true
